spring:
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    password: fms
    url: jdbc:mysql://localhost:3306/fmsdb?useSSL=false
    username: fms
  jackson:
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  main:
    allow-bean-definition-overriding: true  profiles:    active:    - package