logging:
  config: classpath:log4j2-package.xml
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: fms
    url: jdbc:h2:mem:fmsdb
    username: fms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect