logging:
  config: classpath:env-config/package/log4j2.xml
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ENC(ftEDigclRA+AvqPdTumuXw==)
    url: jdbc:h2:mem:fmsdb
    username: ENC(ftEDigclRA+AvqPdTumuXw==)
    data:
    - classpath:env-config/package/data.sql
    schema:
    - classpath:env-config/package/schema.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect